### ISSUE TITLE
스플래쉬 이미지 만들기

### ISSUE THREAD

**Issue by dobeeisfree** [sejinq/HelloStranger#1]

**Comment by dobeeisfree** [comment]
https://github.com/felipecsl/GifImageView

**Comment by sejinq** [comment]
http://gun0912.tistory.com/17
이미지 로더 라이브러리 (gif 로딩)

**Comment by dobeeisfree** [comment]
`http://stackoverflow.com/questions/31082330/show-gif-file-with-glide-image-loading-and-caching-library`

해결!

**Comment by dobeeisfree** [comment]
참고

https://futurestud.io/tutorials/glide-getting-started
http://stackoverflow.com/questions/36556415/displaying-gif-in-imageview-using-glide
