### ISSUE TITLE
xml작업

### ISSUE THREAD

**Issue by sejinq** [sejinq/HelloStranger#16]

**Comment by dobeeisfree** [comment]
![image](https://cloud.githubusercontent.com/assets/15965824/19654258/8b3ea5f2-9a52-11e6-9cde-efd995416a16.png)

맥딜을 참고하려 했음

**Comment by dobeeisfree** [comment]
@sejinq 확인하룜!
https://github.com/sejinq/HelloStranger/pull/19/files
