### ISSUE TITLE
c9 접속해보기

### ISSUE THREAD

**Issue by sejinq** [sejinq/HelloStranger#31]

**Comment by sejinq** [comment]
http://humble.tistory.com/10 
gson 파싱

**Comment by sejinq** [comment]
https://developer.android.com/training/volley/simple.html
web request

**Comment by sejinq** [comment]
https://developer.android.com/training/volley/request.html
json request

**Comment by dobeeisfree** [comment]
api 테스트 도구로서 postman 추천함니다
[크롬웹앱](https://chrome.google.com/webstore/detail/postman/fhbjgbiflinjbdggehcddcbncdddomop?hl=ko)

**Comment by dobeeisfree** [comment]
:+1: 짱짱 포스트맨 :+1: 
![image](https://cloud.githubusercontent.com/assets/15965824/20067640/4cf96658-a559-11e6-893a-02bd7eacf68e.png)
