### ISSUE TITLE
taboo 스위치 리스너 연결하기

### ISSUE THREAD

**Issue by hojunyoo** [sejinq/HelloStranger#9]

**Comment by hojunyoo** [comment]
타부에 쓰이는 국기 아이콘
구글드라이브 디자인>아이콘>국기에 올림

**Comment by dobeeisfree** [comment]
`united-kingdom.png`라는 파일명 대신 `united_kingdom.png`라고 해주세요
안불러와지네여

**Comment by sejinq** [comment]
((Switch)((navigationView.getMenu().findItem(R.id.nav_taboo)).getActionView()).findViewById(R.id.taboo_onoff))

main의 nevigationview에 있는 menu안의 menuitem을 접근해야 view를 가져올 수 있다. 메뉴 바의 switch버튼은 menu item의 actionLayout 안에 들어있기 여기 먼저 접근해서 해당 레이아웃의 뷰를 가져올 수 있다.
((navigationView.getMenu().findItem(찾을 view가 있는 menuitem의 id)).getActionView()).findViewById(view의 id)
